[build]
  publish = "."
  command = ""

# HTML nunca en caché
[[headers]]
  for = "/"
  [headers.values]
  Cache-Control = "no-cache, no-store, must-revalidate"
  Pragma = "no-cache"
  Expires = "0"

[[headers]]
  for = "/*.html"
  [headers.values]
  Cache-Control = "no-cache, no-store, must-revalidate"
  Pragma = "no-cache"
  Expires = "0"

# Manifiestos / SW nunca cacheados
[[headers]]
  for = "/service-worker.js"
  [headers.values]
  Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
  Cache-Control = "no-cache, no-store, must-revalidate"

# Assets cacheados fuerte (con bust de versión)
[[headers]]
  for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/styles.css"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/script.js"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"